### ISSUE TITLE
incomplete privacy api implementation

### ISSUE THREAD

**Issue by danmarsden** [StudiUM/moodle-mod_concordance#2]
Please see: 
https://docs.moodle.org/dev/Privacy_API#Providing_a_way_to_export_user_data

please note - this is not a blocker for approval in the plugins db, but sites sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class correctly,

**Comment by leblangi** [comment]
Hello Dan,

Thanks for pointing that. I believe this has been fixed in the meantime:
https://github.com/StudiUM/moodle-mod_concordance/blob/master/classes/privacy/provider.php
